name: Deploy Dev, then Promote to Prod

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  AWS_REGION: eu-west-1
  TERRAFORM_VERSION: 1.6.0
  # Prod-specific toggles (used during promotion)
  USE_EXISTING_DB_SUBNET_GROUP: "true"
  EXISTING_DB_SUBNET_GROUP_NAME: "devops-job-portal-prod-db-subnet-group"

jobs:
  terraform-plan:
    name: Terraform Plan (Development)
    runs-on: ubuntu-latest
    # No environment gating for dev to keep pipeline simple
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        cd backend
        pip install -r requirements.txt -t .

    - name: Package Lambda functions
      run: |
        cd backend
        # Package all Lambda handlers
        zip -r ../terraform/submit_cv.zip submit_cv.py
        zip -r ../terraform/list_applications.zip list_applications.py
        zip -r ../terraform/get_application.zip get_application.py
        zip -r ../terraform/admin_login.zip admin_login.py

        # Stabilize timestamps to avoid hash drift between jobs
        touch -t 202401010000 ../terraform/*.zip

    - name: Upload Lambda Packages
      uses: actions/upload-artifact@v4
      with:
        name: lambda-packages
        path: terraform/*.zip
        retention-days: 1

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      working-directory: ./terraform
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: |
        terraform init \
          -backend-config="bucket=terraform-state-devops-job-portal" \
          -backend-config="key=dev/terraform.tfstate" \
          -backend-config="region=${{ env.AWS_REGION }}" \
          -backend-config="dynamodb_table=terraform-locks"
      working-directory: ./terraform

    - name: Terraform Workspace
      id: workspace
      run: |
        terraform workspace select dev || terraform workspace new dev
      working-directory: ./terraform

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ./terraform

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -no-color -var="environment=dev" -out=tfplan
      working-directory: ./terraform
      continue-on-error: true

    - name: Upload Plan
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan-dev
        path: terraform/tfplan
        retention-days: 3

    - name: Update Pull Request
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          
          <details><summary>Show Plan</summary>
          
          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`
          
          </details>
          
          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

  deploy:
    name: Deploy to Development
    needs: terraform-plan
    runs-on: ubuntu-latest
    # No environment gating for dev to keep pipeline simple
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        cd backend
        pip install -r requirements.txt -t .

    - name: Download Lambda Packages
      uses: actions/download-artifact@v4
      with:
        name: lambda-packages
        path: terraform/

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=terraform-state-devops-job-portal" \
          -backend-config="key=dev/terraform.tfstate" \
          -backend-config="region=${{ env.AWS_REGION }}" \
          -backend-config="dynamodb_table=terraform-locks"
      working-directory: ./terraform

    - name: Terraform Workspace
      run: |
        terraform workspace select dev
      working-directory: ./terraform

    - name: Download Plan
      uses: actions/download-artifact@v4
      with:
        name: terraform-plan-dev
        path: terraform/

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve tfplan
      working-directory: ./terraform

    - name: Get Terraform Outputs
      id: terraform-output
      run: |
        echo "frontend_bucket=$(terraform output -raw frontend_bucket_name)" >> $GITHUB_OUTPUT
        echo "api_gateway_url=$(terraform output -raw api_gateway_url)" >> $GITHUB_OUTPUT
      working-directory: ./terraform

    - name: Update Frontend Configuration
      run: |
        sed -i "s|https://your-api-gateway-url.execute-api.us-east-1.amazonaws.com/dev|${{ steps.terraform-output.outputs.api_gateway_url }}|g" frontend/js/app.js

    - name: Deploy Frontend to S3
      run: |
        aws s3 sync frontend/ s3://${{ steps.terraform-output.outputs.frontend_bucket }} --delete
        aws s3 cp frontend/index.html s3://${{ steps.terraform-output.outputs.frontend_bucket }}/index.html --cache-control "no-cache"

    - name: Invalidate CloudFront (if exists)
      run: |
        echo "CloudFront invalidation would go here if CDN is configured"
      continue-on-error: true

  test:
    name: Dev Smoke Tests
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init (dev)
      
      run: |
        terraform init \
          -backend-config="bucket=terraform-state-devops-job-portal" \
          -backend-config="key=dev/terraform.tfstate" \
          -backend-config="region=${{ env.AWS_REGION }}" \
          -backend-config="dynamodb_table=terraform-locks"
      working-directory: ./terraform

    - name: Terraform Workspace (dev)
      run: terraform workspace select dev
      working-directory: ./terraform

    - name: Read Terraform Outputs (dev)
      id: dev-out
      run: |
        echo "frontend_bucket=$(terraform output -raw frontend_bucket_name)" >> $GITHUB_OUTPUT
        echo "api_gateway_url=$(terraform output -raw api_gateway_url)" >> $GITHUB_OUTPUT
        echo "frontend_url=http://$(terraform output -raw frontend_bucket_name).s3-website-${{ env.AWS_REGION }}.amazonaws.com" >> $GITHUB_OUTPUT
      working-directory: ./terraform

    - name: Run basic health checks (dev)
      run: |
        set -e
        echo "Checking API: ${{ steps.dev-out.outputs.api_gateway_url }}/applications"
        curl -sSf "${{ steps.dev-out.outputs.api_gateway_url }}/applications" >/dev/null
        echo "Checking Frontend: ${{ steps.dev-out.outputs.frontend_url }}"
        curl -sSf "${{ steps.dev-out.outputs.frontend_url }}" >/dev/null
        echo "✅ Dev environment looks healthy"

  prod-plan:
    name: Terraform Plan (Production)
    needs: [deploy, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Download Lambda Packages
      uses: actions/download-artifact@v4
      with:
        name: lambda-packages
        path: terraform/

    - name: Terraform Init (prod)
      run: |
        terraform init \
          -backend-config="bucket=terraform-state-devops-job-portal" \
          -backend-config="key=prod/terraform.tfstate" \
          -backend-config="region=${{ env.AWS_REGION }}" \
          -backend-config="dynamodb_table=terraform-locks"
      working-directory: ./terraform

    - name: Terraform Workspace (prod)
      run: |
        terraform workspace select prod || terraform workspace new prod
      working-directory: ./terraform

    - name: Import Existing DB Instance (prod)
      run: |
        echo "🔍 Ensuring DB instance is in Terraform state before planning..."
        DB_INSTANCE_ID="devops-job-portal-prod-database"

        if terraform state show aws_db_instance.main >/dev/null 2>&1; then
          echo "✅ DB instance already tracked in Terraform state"
          terraform state show aws_db_instance.main | head -20 || true
        else
          echo "ℹ️  DB instance not in state; attempting Terraform import..."
          set +e
          IMPORT_OUTPUT=$(terraform import aws_db_instance.main "$DB_INSTANCE_ID" 2>&1)
          IMPORT_CODE=$?
          set -e
          echo "$IMPORT_OUTPUT" | tail -n +1 | sed 's/^/terraform import: /'

          if [ $IMPORT_CODE -eq 0 ]; then
            echo "✅ DB instance import successful"
          else
            if echo "$IMPORT_OUTPUT" | grep -qiE 'DBInstanceNotFound|not.?found|NoSuchEntity'; then
              echo "ℹ️  DB instance not found in AWS; Terraform will create it if needed"
            else
              echo "❌ Import failed for a non-NotFound reason (likely permissions or conflict)."
              echo "⛔ Aborting to avoid generating a bad plan that will fail during apply."
              exit 1
            fi
          fi

          if terraform state show aws_db_instance.main >/dev/null 2>&1; then
            echo "📋 Post-import verification:"
            terraform state show aws_db_instance.main | head -20 || true
          fi
        fi
      working-directory: ./terraform

    - name: Ensure DB subnet group not tracked (prod)
      if: env.USE_EXISTING_DB_SUBNET_GROUP == 'true'
      run: |
        echo "🔧 Using existing DB subnet group; ensuring Terraform state does not manage it..."
        if terraform state show aws_db_subnet_group.main >/dev/null 2>&1; then
          echo "🧹 Removing aws_db_subnet_group.main from state to avoid destroy/create"
          terraform state rm aws_db_subnet_group.main
        else
          echo "✅ DB subnet group not in state (good)"
        fi
      working-directory: ./terraform

    - name: Terraform Validate (prod)
      run: terraform validate -no-color
      working-directory: ./terraform

    - name: Terraform Plan (prod)
      run: |
        terraform plan -no-color \
          -var="environment=prod" \
          -var="db_password=${{ secrets.PROD_DB_PASSWORD }}" \
          -var="use_existing_db_subnet_group=${{ env.USE_EXISTING_DB_SUBNET_GROUP }}" \
          -var="existing_db_subnet_group_name=${{ env.EXISTING_DB_SUBNET_GROUP_NAME }}" \
          -out=tfplan
      working-directory: ./terraform

    - name: Upload Plan (prod)
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan-prod
        path: terraform/tfplan
        retention-days: 5

  prod-deploy:
    name: Deploy to Production (Approval Required)
    needs: prod-plan
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Download Lambda Packages
      uses: actions/download-artifact@v4
      with:
        name: lambda-packages
        path: terraform/

    - name: Terraform Init (prod)
      run: |
        terraform init \
          -backend-config="bucket=terraform-state-devops-job-portal" \
          -backend-config="key=prod/terraform.tfstate" \
          -backend-config="region=${{ env.AWS_REGION }}" \
          -backend-config="dynamodb_table=terraform-locks"
      working-directory: ./terraform

    - name: Terraform Workspace (prod)
      run: terraform workspace select prod
      working-directory: ./terraform

    - name: Download Plan (prod)
      uses: actions/download-artifact@v4
      with:
        name: terraform-plan-prod
        path: terraform/

    - name: Terraform Apply (prod)
      run: |
        echo "🚀 Applying Terraform changes to production..."
        terraform apply -auto-approve tfplan
        echo "✅ Terraform deployment completed"
      working-directory: ./terraform

    - name: Get Terraform Outputs (prod)
      id: terraform-output-prod
      run: |
        echo "frontend_bucket=$(terraform output -raw frontend_bucket_name)" >> $GITHUB_OUTPUT
        echo "api_gateway_url=$(terraform output -raw api_gateway_url)" >> $GITHUB_OUTPUT
        echo "frontend_url=$(terraform output -raw frontend_website_url)" >> $GITHUB_OUTPUT
      working-directory: ./terraform

    - name: Update Frontend Configuration (prod)
      run: |
        sed -i "s|https://your-api-gateway-url.execute-api.us-east-1.amazonaws.com/dev|${{ steps.terraform-output-prod.outputs.api_gateway_url }}|g" frontend/js/app.js

    - name: Deploy Frontend to S3 (prod)
      run: |
        aws s3 sync frontend/ s3://${{ steps.terraform-output-prod.outputs.frontend_bucket }} --delete
        aws s3 cp frontend/index.html s3://${{ steps.terraform-output-prod.outputs.frontend_bucket }}/index.html --cache-control "no-cache"

    - name: Production Health Check
      run: |
        echo "🏥 Running production health checks..."
        if curl -f "${{ steps.terraform-output-prod.outputs.api_gateway_url }}/applications" >/dev/null 2>&1; then
          echo "✅ API Gateway is responding"
        else
          echo "⚠️ API Gateway health check failed"
        fi
        if curl -f "http://${{ steps.terraform-output-prod.outputs.frontend_url }}" >/dev/null 2>&1; then
          echo "✅ Frontend is accessible"
        else
          echo "⚠️ Frontend health check failed"
        fi
        echo "✅ Health checks completed"
      continue-on-error: true

    - name: Notify production deployment success
      if: success()
      run: |
        echo "🎉 Production deployment successful!"
        echo "Frontend URL: http://${{ steps.terraform-output-prod.outputs.frontend_url }}"
        echo "API URL: ${{ steps.terraform-output-prod.outputs.api_gateway_url }}"
        echo "Deployed by: @${{ github.actor }}"
        echo "Commit: ${{ github.sha }}"